server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: userservice #user服务的服务名称
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

    #配置eureka的信息
eureka:
  client:
    fetch-registry: true                           # 表示是否向Eureka Server注册
    register-with-eureka: true                     # 表示是否从Eureka Server获取注册信息
    service-url:
      defaultZone: http://server1:10086/eureka/,http://server2:10086/eureka/
management:
  endpoint:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true