server:
 port: 8769
spring:
 application:
  name: service-turbine
security:
 basic:
  enable: false
turbine:
 instanceUrlSuffix: /hystrix.stream
 aggregator:
  clusterConfig: default
 appConfig: eureka-hystrix-client
 clusterNameExpression: new String("default")
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:7000/eureka/