server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
eureka:
  client:
    fetch-registry: true                           # 表示是否向Eureka Server注册
    register-with-eureka: true                     # 表示是否从Eureka Server获取注册信息
    service-url:
      defaultZone: http://server1:10086/eureka/,http://server2:10086/eureka/
management:
  endpoint:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
usersevice:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
ribbon:
  eager-load:
    enabled: true #开启饥饿加载
    clients: userservice #指定对usserservice这个服务饥饿加载

##feign的自定义配置方式一 全局配置
feign:
  hystrix:
    enabled: true
#  client:
#    config:
#      default:
#        logger-level: FULL

#  feign优化
#  httpclient:
#    enabled: true
#    max-connections: 200
#    max-connections-per-route: 50
hystrix:
  dashboard:
    proxy-stream-allow-list: "localhost"

