server:
  port: 10086                                        # 服务器端口号10086
spring:
  application:                                      #端口号名称配置
    name: eurekaserver
eureka:
  client:
    fetch-registry: true                           # 表示是否向Eureka Server注册
    register-with-eureka: true                     # 表示是否从Eureka Server获取注册信息
    service-url:
      defaultZone: http://server1:10086/eureka/

management:
  endpoint:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

